import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function GET(request: Request) {
  try {
    // Get portfolio size from query param (optional)
    const { searchParams } = new URL(request.url);
    const portfolioSize = parseFloat(searchParams.get('size') || '10000');

    // Read from the JSON file generated by Python scripts
    const dataPath = path.join(process.cwd(), 'data', 'signals.json');
    const fileContent = fs.readFileSync(dataPath, 'utf-8');
    const data = JSON.parse(fileContent);

    // Build portfolio positions from signals
    const positions = data.signals
      .filter((s: { targetAllocation: number }) => s.targetAllocation > 0)
      .map((signal: { asset: string; targetAllocation: number; signal: string; conviction: string; category: string; quadrant: string }) => {
        const dollarAmount = signal.targetAllocation * portfolioSize;

        return {
          asset: signal.asset,
          allocation: signal.targetAllocation,
          dollarAmount,
          signal: signal.signal,
          conviction: signal.conviction,
          category: signal.category,
          quadrant: signal.quadrant,
        };
      });

    // Calculate allocations by category
    const categoryAllocations: Record<string, number> = {};
    positions.forEach((pos: { category: string; allocation: number }) => {
      const cat = pos.category || 'other';
      categoryAllocations[cat] = (categoryAllocations[cat] || 0) + pos.allocation;
    });

    // Calculate total leverage
    const totalLeverage = positions.reduce((sum: number, pos: { allocation: number }) => sum + pos.allocation, 0);

    const response = {
      portfolioSize,
      totalLeverage: Math.round(totalLeverage * 100) / 100,
      numPositions: positions.length,
      positions,
      categoryAllocations,
      regime: {
        primaryQuadrant: data.regime.primaryQuadrant,
        secondaryQuadrant: data.regime.secondaryQuadrant,
      },
      timestamp: data.generatedAt,
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error('Error fetching portfolio:', error);
    return NextResponse.json(
      { error: 'Failed to fetch portfolio' },
      { status: 500 }
    );
  }
}
