import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function GET() {
  try {
    // Read from the JSON file generated by Python scripts
    const dataPath = path.join(process.cwd(), 'data', 'signals.json');
    const fileContent = fs.readFileSync(dataPath, 'utf-8');
    const data = JSON.parse(fileContent);
    const regime = data.regime;

    const response = {
      quadrant: regime.primaryQuadrant,
      primaryQuadrant: regime.primaryQuadrant,
      secondaryQuadrant: regime.secondaryQuadrant,
      growthDirection: regime.growthDirection,
      inflationDirection: regime.inflationDirection,
      confidence: regime.confidence,
      daysInRegime: regime.daysInRegime,
      lastChange: regime.lastChange,
      timestamp: data.generatedAt,
      quadrantInfo: getQuadrantInfo(regime.primaryQuadrant),
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error('Error fetching regime:', error);
    return NextResponse.json(
      { error: 'Failed to fetch regime data' },
      { status: 500 }
    );
  }
}

function getQuadrantInfo(quadrant: string) {
  const info: Record<string, { name: string; description: string; color: string }> = {
    Q1: {
      name: 'Goldilocks',
      description: 'Growth rising, inflation falling. Risk-on environment favoring growth assets.',
      color: '#22c55e',
    },
    Q2: {
      name: 'Reflation',
      description: 'Growth rising, inflation rising. Commodities and value stocks outperform.',
      color: '#f97316',
    },
    Q3: {
      name: 'Stagflation',
      description: 'Growth falling, inflation rising. Defensive positioning with inflation hedges.',
      color: '#ef4444',
    },
    Q4: {
      name: 'Deflation',
      description: 'Growth falling, inflation falling. Flight to quality, bonds outperform.',
      color: '#3b82f6',
    },
  };

  return info[quadrant] || { name: quadrant, description: '', color: '#6b7280' };
}
