import { NextResponse } from 'next/server';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function GET() {
  try {
    // Run the Python signal generator script
    const rootDir = path.join(process.cwd(), '..', '..');
    const scriptPath = path.join(rootDir, 'scripts', 'update_signals.py');

    try {
      execSync(`python ${scriptPath}`, {
        cwd: rootDir,
        timeout: 60000, // 1 minute timeout
        stdio: 'pipe',
      });
    } catch (execError) {
      console.error('Python script error (using cached data):', execError);
      // Fall through to read cached data
    }

    // Read from the JSON file generated by Python scripts
    const dataPath = path.join(process.cwd(), 'data', 'signals.json');
    const fileContent = fs.readFileSync(dataPath, 'utf-8');
    const data = JSON.parse(fileContent);

    const response = {
      signals: data.signals,
      meta: {
        tier: 'free',
        totalSignals: data.signals.length,
        totalLeverage: data.signals.reduce((sum: number, s: { targetAllocation: number }) => sum + s.targetAllocation, 0),
        timestamp: data.generatedAt,
        primaryQuadrant: data.regime.primaryQuadrant,
        secondaryQuadrant: data.regime.secondaryQuadrant,
      },
      regime: data.regime,
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error('Error fetching signals:', error);
    return NextResponse.json(
      { error: 'Failed to fetch signals' },
      { status: 500 }
    );
  }
}
