import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function GET() {
  try {
    // Read from the JSON file generated by Python scripts
    const dataPath = path.join(process.cwd(), 'data', 'signals.json');
    const fileContent = fs.readFileSync(dataPath, 'utf-8');
    const data = JSON.parse(fileContent);

    const response = {
      signals: data.signals,
      meta: {
        tier: 'free',
        totalSignals: data.signals.length,
        totalLeverage: data.signals.reduce((sum: number, s: { targetAllocation: number }) => sum + s.targetAllocation, 0),
        timestamp: data.generatedAt,
        primaryQuadrant: data.regime.primaryQuadrant,
        secondaryQuadrant: data.regime.secondaryQuadrant,
      },
      regime: data.regime,
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error('Error fetching signals:', error);
    return NextResponse.json(
      { error: 'Failed to fetch signals' },
      { status: 500 }
    );
  }
}
